// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
)

type FsNode struct {
	ID         int64
	ParentID   sql.NullInt64
	Name       string
	Kind       int64
	CreatedAt  int64
	ModifiedAt int64
	Data       []byte
}

type FsNodeName struct {
	Name string
}
