// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"
	"database/sql"
)

const deleteNode = `-- name: DeleteNode :exec
DELETE FROM nodes WHERE id = ?
`

func (q *Queries) DeleteNode(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteNode, id)
	return err
}

const getChild = `-- name: GetChild :one
SELECT id, kind FROM nodes WHERE parent_id = ? AND name = ?
`

type GetChildParams struct {
	ParentID sql.NullInt64
	Name     string
}

type GetChildRow struct {
	ID   int64
	Kind int64
}

func (q *Queries) GetChild(ctx context.Context, arg GetChildParams) (GetChildRow, error) {
	row := q.db.QueryRowContext(ctx, getChild, arg.ParentID, arg.Name)
	var i GetChildRow
	err := row.Scan(&i.ID, &i.Kind)
	return i, err
}

const getData = `-- name: GetData :one
SELECT data FROM nodes WHERE id = ?
`

func (q *Queries) GetData(ctx context.Context, id int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getData, id)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const hasChildren = `-- name: HasChildren :one
SELECT EXISTS (SELECT 1 FROM nodes WHERE parent_id = ?)
`

func (q *Queries) HasChildren(ctx context.Context, parentID sql.NullInt64) (bool, error) {
	row := q.db.QueryRowContext(ctx, hasChildren, parentID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertDir = `-- name: InsertDir :execlastid

INSERT INTO nodes (parent_id, name, kind, created_at, modified_at, data)
VALUES (?, ?, 0, ?, ?, NULL)
`

type InsertDirParams struct {
	ParentID   sql.NullInt64
	Name       string
	CreatedAt  int64
	ModifiedAt int64
}

// Drivers disagree on how a nil []byte binds (NULL vs empty blob), so
// directories use a literal NULL and files must always pass a non-nil slice.
func (q *Queries) InsertDir(ctx context.Context, arg InsertDirParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertDir,
		arg.ParentID,
		arg.Name,
		arg.CreatedAt,
		arg.ModifiedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertFile = `-- name: InsertFile :execlastid
INSERT INTO nodes (parent_id, name, kind, created_at, modified_at, data)
VALUES (?, ?, 1, ?, ?, ?)
`

type InsertFileParams struct {
	ParentID   sql.NullInt64
	Name       string
	CreatedAt  int64
	ModifiedAt int64
	Data       []byte
}

func (q *Queries) InsertFile(ctx context.Context, arg InsertFileParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertFile,
		arg.ParentID,
		arg.Name,
		arg.CreatedAt,
		arg.ModifiedAt,
		arg.Data,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const insertRoot = `-- name: InsertRoot :exec
INSERT OR IGNORE INTO nodes (id, parent_id, name, kind, created_at, modified_at)
VALUES (1, NULL, '', 0, ?, ?)
`

type InsertRootParams struct {
	CreatedAt  int64
	ModifiedAt int64
}

func (q *Queries) InsertRoot(ctx context.Context, arg InsertRootParams) error {
	_, err := q.db.ExecContext(ctx, insertRoot, arg.CreatedAt, arg.ModifiedAt)
	return err
}

const isAncestor = `-- name: IsAncestor :one
WITH RECURSIVE anc(id) AS (
	SELECT CAST(?2 AS INTEGER)
	UNION ALL
	SELECT n.parent_id FROM nodes n JOIN anc ON n.id = anc.id WHERE n.parent_id IS NOT NULL
)
SELECT COUNT(*) FROM anc WHERE id = ?1
`

type IsAncestorParams struct {
	AncestorID int64
	NodeID     int64
}

// Reports whether ancestor_id is node_id itself or one of its ancestors.
func (q *Queries) IsAncestor(ctx context.Context, arg IsAncestorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isAncestor, arg.AncestorID, arg.NodeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listChildren = `-- name: ListChildren :many
SELECT name, kind, CAST(COALESCE(length(data), 0) AS INTEGER) AS size, created_at, modified_at
FROM nodes WHERE parent_id = ? ORDER BY name
`

type ListChildrenRow struct {
	Name       string
	Kind       int64
	Size       int64
	CreatedAt  int64
	ModifiedAt int64
}

func (q *Queries) ListChildren(ctx context.Context, parentID sql.NullInt64) ([]ListChildrenRow, error) {
	rows, err := q.db.QueryContext(ctx, listChildren, parentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChildrenRow
	for rows.Next() {
		var i ListChildrenRow
		if err := rows.Scan(
			&i.Name,
			&i.Kind,
			&i.Size,
			&i.CreatedAt,
			&i.ModifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveNode = `-- name: MoveNode :exec
UPDATE nodes SET parent_id = ?, name = ? WHERE id = ?
`

type MoveNodeParams struct {
	ParentID sql.NullInt64
	Name     string
	ID       int64
}

func (q *Queries) MoveNode(ctx context.Context, arg MoveNodeParams) error {
	_, err := q.db.ExecContext(ctx, moveNode, arg.ParentID, arg.Name, arg.ID)
	return err
}

const statNode = `-- name: StatNode :one
SELECT name, kind, CAST(COALESCE(length(data), 0) AS INTEGER) AS size, created_at, modified_at
FROM nodes WHERE id = ?
`

type StatNodeRow struct {
	Name       string
	Kind       int64
	Size       int64
	CreatedAt  int64
	ModifiedAt int64
}

func (q *Queries) StatNode(ctx context.Context, id int64) (StatNodeRow, error) {
	row := q.db.QueryRowContext(ctx, statNode, id)
	var i StatNodeRow
	err := row.Scan(
		&i.Name,
		&i.Kind,
		&i.Size,
		&i.CreatedAt,
		&i.ModifiedAt,
	)
	return i, err
}

const touch = `-- name: Touch :exec
UPDATE nodes SET modified_at = ? WHERE id = ?
`

type TouchParams struct {
	ModifiedAt int64
	ID         int64
}

func (q *Queries) Touch(ctx context.Context, arg TouchParams) error {
	_, err := q.db.ExecContext(ctx, touch, arg.ModifiedAt, arg.ID)
	return err
}

const updateData = `-- name: UpdateData :exec
UPDATE nodes SET data = ?, modified_at = ? WHERE id = ?
`

type UpdateDataParams struct {
	Data       []byte
	ModifiedAt int64
	ID         int64
}

func (q *Queries) UpdateData(ctx context.Context, arg UpdateDataParams) error {
	_, err := q.db.ExecContext(ctx, updateData, arg.Data, arg.ModifiedAt, arg.ID)
	return err
}
